"""Dense semantic retrieval.

TODO:
- Query Qdrant dense vectors generated by sentence-transformers or Ollama embeddings.
- Add metadata filters for department, ACL, version, and document type.
"""


class DenseRetriever:
    """Semantic vector retriever for child chunks."""

    def retrieve(self, query: str, top_k: int) -> list[dict]:
        """Return dense retrieval candidates."""

        raise NotImplementedError("Dense retrieval will be implemented with Qdrant search.")

